on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  test-jdk8:
    name: "rawhide - jdk8"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
        include:
          - jdkconf: JDK 8
            jdkver: "8"
    steps:
      - uses: actions/checkout@v3
      - name: Init
        run: |
          sudo apt-get update
          sudo apt-get install mock wget python3
      - name: Download Rpms
        run: |
          wget -P "rpms/" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-8-jdk-8.0.372.0.0.7-1.x86_64.rpm" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-8-jre-8.0.372.0.0.7-1.x86_64.rpm"
      - name: Run
        run: ./generic_runner/runner.sh
      - name: Pack results
        if: ${{ always() }}
        run: |
          tar -cf "results-jdk${{ matrix.jdkver }}.tar.gz" jtregLogs/ verbose_log_file.log jsf.log
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "results-jdk${{ matrix.jdkver }}.tar.gz"
        continue-on-error: true
  test-jdk11:
    name: "rawhide - jdk11"
    runs-on: "ubuntu-latest"
    container: "quay.io/fedora/fedora:rawhide"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 11
        include:
          - jdkconf: JDK 11
            jdkver: "11"
    steps:
      - uses: actions/checkout@v3
      - name: Init
        run: |
          dnf -y install mock wget python3
          useradd tester
          usermod -a -G wheel tester
          usermod -a -G mock tester
          su tester
      - name: Download Rpms
        run: |
          wget -P "rpms/" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-11-jdk-11.0.19.0.0.7-1.x86_64.rpm" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-11-jre-11.0.19.0.0.7-1.x86_64.rpm"
      - name: Run
        run: ./generic_runner/runner.sh
      - name: Pack results
        if: ${{ always() }}
        run: |
          tar -cf "results-jdk${{ matrix.jdkver }}.tar.gz" jtregLogs/ verbose_log_file.log jsf.log
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "results-jdk${{ matrix.jdkver }}.tar.gz"
        continue-on-error: true
  test-jdk17:
    name: "rawhide - jdk17"
    runs-on: "ubuntu-latest"
    container: "quay.io/fedora/fedora:rawhide"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 17
        include:
          - jdkconf: JDK 17
            jdkver: "17"
    steps:
      - uses: actions/checkout@v3
      - name: Init
        run: |
          dnf -y install mock wget python3
      - name: Download Rpms
        run: |
          wget -P "rpms/" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-17-jdk-17.0.7.0.0.7-1.x86_64.rpm" "https://packages.adoptium.net/artifactory/rpm/rhel/8/x86_64/Packages/temurin-17-jre-17.0.7.0.0.7-1.x86_64.rpm"
      - name: Run
        run: ./generic_runner/runner.sh
      - name: Pack results
        if: ${{ always() }}
        run: |
          tar -cf "results-jdk${{ matrix.jdkver }}.tar.gz" jtregLogs/ verbose_log_file.log jsf.log
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: "results-jdk${{ matrix.jdkver }}.tar.gz"
        continue-on-error: true

